config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#index"
  resources :games ,only: :index do
    collection do
      get "quize"
      get "timer"
      get "omikuji"
      get "slot"
      get "touch"
    end
  end

  resources :points, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramaters, if: :devise_controller?

  def configure_permitted_paramaters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :new_point
  before_action :move_to_top, only: [:quize, :timer, :slot, :touch, :omikuji]

  def index
  end

  def quize
  end

  def timer
  end

  def omikuji
  end

  def slot
  end

  def touch
  end

  private
  def move_to_top
    redirect_to action: :index unless user_signed_in?
  end

  def new_point
    @point = Point.new
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def create
    @point = Point.new(point_params)
    if @point.save
      @points = Point.where(user_id: current_user.id).count
      # binding.pry
      respond_to do |format|
        format.html #{redirect_to root_path}
        format.json { render json: @points}
      end
    else
      redirect_to :root
    end
  end

  private
  def point_params
    params.require(:point).permit(:point).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/games/index.html.haml
%ul.gamesBtn
  %li
    = link_to "LEVEL1", timer_games_path, class: "gameBtn level1"
  %li
    = link_to "LEVEL2", omikuji_games_path, class: "gameBtn level2"
  %li
    = link_to "LEVEL3", quize_games_path, class: "gameBtn level3"
  %li
    = link_to "LEVEL4", touch_games_path, class: "gameBtn level4"
  %li
    = link_to "LEVEL5", slot_games_path, class: "gameBtn level5"

app/views/games/omikuji.html.haml
#omikuji
  %p omikuji
  #btn ?
  #selectResult.hidden
    = render "layouts/result"


= javascript_include_tag 'games/omikuji.js', 'data-turbolinks-track': 'load'
= javascript_include_tag 'games/point_up.js'

app/views/games/quize.html.haml
#quize
  %p quize
  %section.container
    %p#question
    %ul#choices
    #btn.disabled Next
    %section#result.hidden
      %p
      %a{:href => ""} Replay?
  #selectResult.hidden
    = render "layouts/result"

= javascript_include_tag 'games/quize.js'
= javascript_include_tag 'games/point_up.js'

app/views/games/slot.html.haml
#slot
  %p slot
  %main
  #spin SPIN
  #fever FEVER MODE
  #selectResult.hidden
    = render "layouts/result"
= javascript_include_tag 'games/slot.js'
= javascript_include_tag 'games/point_up.js'

app/views/games/timer.html.haml
#timerPage
  %p timer
  .container
    #timer 00:00.000
    .controls
      #start.btn Start
      #stop.btn Stop
      #reset.btn Reset
  #selectResult.hidden
    = render "layouts/result"

= javascript_include_tag 'games/timer.js'
= javascript_include_tag 'games/point_up.js'

app/views/games/touch.html.haml
#touch
  %p touch
  #container
    #timer 0.00
    %ul#board
    #btn START
  #selectResult.hidden
    = render "layouts/result"

= javascript_include_tag 'games/touch.js'
= javascript_include_tag 'games/point_up.js'

app/views/layouts/_result.html.haml
.message
  %h3 未来の自分に投資する？
.form
  = form_with model: @point, id: :kokki_form do |f|
    .form_num.display_none
      = f.label :ポイント
      = f.number_field :point, value: 1
    .form_sumbit
      = f.submit "KOKKI!" ,id: "kokki_btn"
.select_btn
  %ul
    %li
      = link_to "TOPへ", root_path, class: "to_top"
    %li.to_youtube
      = link_to "今日はいいや！", "https://www.youtube.com/"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kokki
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)
    %header
      .header-left
        = link_to root_path do
          %h1.logo Kokki
      .header-right
        - if user_signed_in?
          %ul.user_top_info
            %li.user_top_info__name
              = "#{current_user.name} さんのKOKKI "
            %li.user_top_info__point
              - if (Point.where(user_id: current_user.id).count != nil)
                = "#{Point.where(user_id: current_user.id).count} ポイント"
              - else
                0 ポイント
          = link_to 'プロフィール変更', edit_user_registration_path
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          = link_to "新規登録", new_user_registration_path
          = link_to "ログイン", new_user_session_path
    = yield